"""
graph/state.py
--------------
Defines the CandidateState TypedDict — the single source of truth that flows
through every node in the LangGraph conversation graph.

All fields are Optional so the graph can be initialized with minimal data
and progressively enriched as the conversation advances.
"""

from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


# ---------------------------------------------------------------------------
# Conversation Stages
# ---------------------------------------------------------------------------
# Ordered stages the conversation moves through. Used in edges.py routing
# and in the Streamlit sidebar progress tracker.
STAGES = [
    "greeting",
    "info_gather",
    "tech_stack",
    "generate_questions",
    "interview",
    "farewell",
]

# Fields we must collect before moving to tech stack declaration.
# Ordered as we want to ask them conversationally.
REQUIRED_INFO_FIELDS = [
    "full_name",
    "email",
    "phone",
    "years_of_experience",
    "desired_positions",
    "current_location",
]

# Keywords that trigger an immediate graceful exit from any stage.
EXIT_KEYWORDS = {
    "exit", "quit", "bye", "goodbye", "stop", "end",
    "cancel", "leave", "done", "finish",
}


# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------
class CandidateState(TypedDict):
    """
    Complete state for one candidate screening session.

    LangGraph passes this dict between nodes. Each node returns a partial
    dict of only the fields it changes — LangGraph merges them automatically.
    The `messages` field uses the built-in `add_messages` reducer so new
    messages are appended rather than overwriting the history.
    """

    # ------------------------------------------------------------------
    # Conversation Memory
    # `add_messages` reducer: appends new messages instead of replacing.
    # Holds the full human/AI message history for LLM context window.
    # ------------------------------------------------------------------
    messages: Annotated[list, add_messages]

    # ------------------------------------------------------------------
    # Candidate Profile — populated incrementally during info_gather
    # ------------------------------------------------------------------
    full_name: Optional[str]
    email: Optional[str]
    phone: Optional[str]
    years_of_experience: Optional[int]       # raw int, e.g. 4
    desired_positions: Optional[list[str]]   # e.g. ["Backend Engineer", "SRE"]
    current_location: Optional[str]
    tech_stack: Optional[list[str]]          # e.g. ["Python", "FastAPI", "Redis"]

    # ------------------------------------------------------------------
    # Interview Question Bank
    # Populated once by generate_questions_node; consumed during interview.
    # Structure: { "Python": ["q1", "q2", "q3"], "FastAPI": [...], ... }
    # ------------------------------------------------------------------
    tech_questions: Optional[dict]           # keyed by technology name
    question_queue: Optional[list]           # flat list: [{"tech": t, "q": q}, ...]
    current_question_index: int              # pointer into question_queue
    candidate_answers: Optional[list]        # [{"tech", "question", "answer"}, ...]

    # ------------------------------------------------------------------
    # Flow Control
    # ------------------------------------------------------------------
    current_stage: str                       # one of STAGES
    info_fields_collected: list[str]         # tracks which REQUIRED_INFO_FIELDS are done
    exit_triggered: bool                     # True if EXIT_KEYWORDS detected
    is_complete: bool                        # True after farewell node fires

    # ------------------------------------------------------------------
    # Bonus Features
    # ------------------------------------------------------------------
    sentiment: Optional[str]                 # "positive" | "neutral" | "negative"
    language: str                            # default "English"; supports multilingual
    session_id: str                          # UUID for data_handler storage


# ---------------------------------------------------------------------------
# Factory: build a clean initial state for a new session
# ---------------------------------------------------------------------------
def initial_state(session_id: str, language: str = "English") -> CandidateState:
    """
    Returns a fresh CandidateState for a new candidate session.

    Args:
        session_id: UUID string generated by app.py per browser session.
        language:   Language the chatbot will respond in (default English).
    """
    return CandidateState(
        messages=[],

        # Candidate profile — all None until gathered
        full_name=None,
        email=None,
        phone=None,
        years_of_experience=None,
        desired_positions=None,
        current_location=None,
        tech_stack=None,

        # Question bank — populated by generate_questions_node
        tech_questions=None,
        question_queue=None,
        current_question_index=0,
        candidate_answers=[],

        # Flow control
        current_stage="greeting",
        info_fields_collected=[],
        exit_triggered=False,
        is_complete=False,

        # Bonus
        sentiment="neutral",
        language=language,
        session_id=session_id,
    )


# ---------------------------------------------------------------------------
# Helpers used by nodes and edges
# ---------------------------------------------------------------------------
def get_missing_info_fields(state: CandidateState) -> list[str]:
    """Returns REQUIRED_INFO_FIELDS not yet collected, in order."""
    return [f for f in REQUIRED_INFO_FIELDS if f not in state["info_fields_collected"]]


def all_info_collected(state: CandidateState) -> bool:
    """True when every required info field has been gathered."""
    return set(REQUIRED_INFO_FIELDS).issubset(set(state["info_fields_collected"]))


def get_next_question(state: CandidateState) -> Optional[dict]:
    """
    Returns the next unanswered question dict {"tech": str, "q": str},
    or None if the interview is complete.
    """
    queue = state.get("question_queue") or []
    idx = state.get("current_question_index", 0)
    if idx < len(queue):
        return queue[idx]
    return None


def has_more_questions(state: CandidateState) -> bool:
    """True if there are still questions left to ask."""
    return get_next_question(state) is not None


def exit_detected(state: CandidateState) -> bool:
    """Checks the latest human message for exit keywords."""
    messages = state.get("messages", [])
    for msg in reversed(messages):
        # Only inspect HumanMessages
        if hasattr(msg, "type") and msg.type == "human":
            text = msg.content.lower()
            return any(kw in text.split() for kw in EXIT_KEYWORDS)
        # Handle plain dicts if messages stored that way
        if isinstance(msg, dict) and msg.get("role") == "human":
            text = msg.get("content", "").lower()
            return any(kw in text.split() for kw in EXIT_KEYWORDS)
        break  # only check latest message
    return False